spring.application.name=carely-api
spring.datasource.url=jdbc:postgresql://localhost:5432/carely
spring.datasource.username=postgres
spring.datasource.password=postgres
server.web.error.include-message=always
