<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">

	<modelVersion>4.0.0</modelVersion>

	<parent>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-parent</artifactId>
		<version>4.1.0</version>
		<relativePath/> <!-- lookup parent from repository -->
	</parent>


	<groupId>com.carely</groupId>
	<artifactId>carely-api</artifactId>
	<version>0.0.1-SNAPSHOT</version>

	<packaging>pom</packaging>

	<properties>
		<java.version>21</java.version>

		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>

		<maven.compiler.release>21</maven.compiler.release>
		<jooq.jdbc.url>jdbc:postgresql://localhost:5432/carely</jooq.jdbc.url>
		<jooq.jdbc.user>postgres</jooq.jdbc.user>
		<jooq.jdbc.credential>${env.CARELY_DB_TOKEN}</jooq.jdbc.credential>
	</properties>

	<!-- Child modules -->
	<modules>
		<module>carely-server</module>
		<module>db-migrations</module>
		<module>jooq-generation</module>
		<module>carely-users</module>
		<module>carely-auth</module>
		<module>carely-doctors</module>
	</modules>




</project>
